name: CD - Update Lambda with New Container Image from ECR

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch

jobs:
  update_lambda:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Update Lambda function with the latest container image from ECR
    - name: Update Lambda with new image from ECR
      run: |
        IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$AWS_ECR_REPO_NAME:latest
        
        # Update Lambda with the container image
        aws lambda update-function-code \
          --function-name $AWS_LAMBDA_FUNCTION_NAME \
          --image-uri $IMAGE_URI \
          --region $AWS_REGION
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
